### PR TITLE
feat: Enhance support for a wider variety of video URL formats.

### PR DESCRIPTION
**Pull request by nicky-dev**

### CODE REVIEW

**Comment by hzrd149** [comment]
The code and MR itself looks good however I don't think supporting Twitch, Facebook, YouTube, or any other proprietary streams is a good idea. 
While its pretty easy for web clients like noStrudel to load the stream in an iframe. other native clients like Amethyst wont be able to play or control the stream.
Right now while NIP-53 doesn't have any restrictions on what type of URL can go in the "streaming" tag. it dose suggest using m3u8 and HLS streaming since that format is open and is supported on every platform.

**Comment by nicky-dev** [comment]
Thank you @hzrd149 for helping review the code. I agree with you regarding the streaming URL part. However, in the case of the recording URL, do you think we can make it flexible to support?

**Comment by hzrd149** [comment]
Whats the use-case for recorded URLs though? I cant imagine the chat will be very useful. would it just be to have a back catalogue of videos?

Also if the `streaming` or `recording` field is set to a twitch stream or vod URL then you would still need to provide a thumbnail image for the event. otherwise it would show as empty

**Comment by nicky-dev** [comment]
We use it in cases where we want to watch replays. Currently, we have to create a note and insert the YouTube link into the note so that people in the community can watch replays.

**Comment by nicky-dev** [comment]
Thanks @hzrd149 for working. I agree with you. Since Twitch and YouTube are not open standards, it may not be suitable to implement support for them, and I think we can close the pull request.

**Comment by hzrd149** [comment]
closing. and thanks for taking the time to build out a working PR

**Pull request closed without merging**
