### PR TITLE
chore: update bitcoin connect dependency

### PR DESCRIPTION
**Pull request by rolznz**
Hi! the new version of Bitcoin Connect contains 3 new connectors: Mutiny, Lnbits, and LNC - which should allow more users to connect their lightning wallets to Nostrudel.

I wrote an update about it on BOLT FUN: https://bolt.fun/story/three-new-connectors-lnc-lnbits-mutiny--1177

### CODE REVIEW

**Comment by hzrd149** [comment]
The update looks awesome, just tested it locally.
Only issue I found is it that it calls "getBalance" as soon as the app opens. I can always check the "remember choice" option but this doesn't seem like good UX
Normally this isn't a big deal, but personally I never check the "remember choice" option. so this would get pretty annoying for me or anyone else who wants to manually approve things.

**Comment by weex** [comment]
Is it hard to delay the getBalance call until it's needed? Might be good to merge this then allow someone else to fix that. React is not my specialty but in the interest of getting PRs merged I'd be willing to dig into it if someone has an idea of how it can be done.

**Comment by rolznz** [comment]
@hzrd149 I agree, let's fix that first - thanks!

@weex, we have an open issue: https://github.com/getAlby/bitcoin-connect/issues/69

Basically we request the balance from the store to make sure it's available to display on the button/modal. But that makes no sense if the modal and button aren't even visible on the page.

I'll try to fix it and then I will update this PR.

**Comment by rolznz** [comment]
@hzrd149 I fixed it so it'll only request the balance if the button is mounted on the page. It won't request the balance on the home page, but it will on the settings page if you're connected to Bitcoin Connect and you refresh the page (even though the lightning section is hidden by default).

I will see if I can improve this in a follow up PR.

**Comment by rolznz** [comment]
@hzrd149 thinking about the button mounting issue - I think it actually has to be fixed on the nostrudel side - only render the button component if the lightning accordion item is actually open. I pushed a small change for this, what do you think?

**Comment by hzrd149** [comment]
@rolznz the issue seems to be fixed. Just tested it and it only requests the balance when you open the lightning settings and the button is shown.
Long term it would be great to have an option to disable showing the balance all together.

Also love the addition of LNC, its another thing I've had on my todo list but haven't had the time to learn

P.S. the build size only increased 10kB :tada:

**Pull request merged**
